#!/bin/sh

rm -r pkg
mkdir pkg
cp index.html pkg/
cp s.css pkg/
cp jsfxr.js pkg/
echo 'COMPRESSING...'
yuicompressor -v -o pkg/g.js g.js
cd pkg
echo ''
echo 'ZIPPING...'
zip -9 game.zip index.html g.js jsfxr.js s.css
cd ..
echo ''
echo 'SIZE: '
ls -l pkg/game.zip | awk '{ print $5 }'
